Nike Store Webpage
Swarzstein/review-pool-request pull request #1
Opened 2022-08-22 17:02 UTC by Swarzstein

Web page to display the new Nike products.

2022-08-22 21:59 UTC, vickymarz requested changes
Hi @Swarzstein , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project, that does not have any reviews at all. Kindly add reviews as specified in the requirement and submit again 👍🏼 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-23 00:13 UTC, Svartstein commented on index.html
> +
Hello! The page is looking good! I see you've forgoten to close the header tag though, it might help you in the future to always check your code for unclosed tags 😉 .

2022-08-23 00:13 UTC, Svartstein commented on index.html
> +</head>
I recommend you to use the "!" shortcut if you are using Visual Studio Code because it puts all the basic template of an HTML5 page. I suggest you to check the linter errors to fix your code and apply the best HTML & CSS practices.

2022-08-23 00:13 UTC, Svartstein commented on index.html
> +      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
It's a good practice to apply styles from the css file and not directly in the html line, try to use classes to apply the styles that you want.

2022-08-23 00:13 UTC, Svartstein commented on README.md
> +Note: Be sure to add <link rel="stylesheet" href="styles.css"> in your HTML to link your stylesheet and apply your CSS
Please, use [this template](https://github.com/microverseinc/readme-template) to add a description to your project, but remember to customize it to fit your project. It will help your Repo look more profecional,
And it would be good if you add a licence to your project, I recommend you to use MIT License. Click in "add file" and create a file called "LICENSE" and you'll se available the options of choosing a template for your license.

2022-08-23 00:17 UTC, vickymarz approved these changes
Hi @Swarzstein , 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- Good use of inline comments ✅ 
- Good use of emojis ✅ 
- Review is clear and polite ✅ 


<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 19:24 UTC, merged